name: 不用管报错，实际上已经同步过去了

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 部署到服务器
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的PRIVATE_KEY中 
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: "./"
          
          # 服务器域名/IP
          REMOTE_HOST: wiki.tatysmp.love
          
          # 服务器默认用户名为root
          REMOTE_USER: "root"
          
          # 目标目录
          TARGET: '/www/wwwroot/wiki.tatysmp.love'
          
          # 排除目录
          EXCLUDE: "./.github/"


